-- CreateTable
CREATE TABLE "tb_ativos" (
    "ID_ATIVOS" TEXT NOT NULL,
    "DS_ESTADO" TEXT NOT NULL,
    "NR_ESTADO" INTEGER NOT NULL,
    "ID_USER_INC" TEXT NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "tb_ativos_pkey" PRIMARY KEY ("ID_ATIVOS")
);

-- CreateTable
CREATE TABLE "TB_EXECUTIVO" (
    "ID_EXECUTIVO" TEXT NOT NULL,
    "NR_CPF" TEXT NOT NULL,
    "NR_CNPJ" TEXT NOT NULL,
    "DS_ESTADO" TEXT NOT NULL,
    "TP_ATIVO" TEXT NOT NULL,
    "DS_USUARIO" TEXT NOT NULL,
    "DS_SENHA" TEXT NOT NULL,
    "VL_RECEITA" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_EXECUTIVO_pkey" PRIMARY KEY ("ID_EXECUTIVO")
);

-- CreateTable
CREATE TABLE "TB_REVENDA" (
    "ID_REVENDA" TEXT NOT NULL,
    "ID_UPLINE_NV1" TEXT NOT NULL,
    "ID_UPLINE_NV2" TEXT NOT NULL,
    "ID_UPLINE_NV3" TEXT NOT NULL,
    "ID_ENDERECO" TEXT NOT NULL,
    "NV_DOWNLINE" TEXT NOT NULL,
    "DS_CARGO" TEXT NOT NULL,
    "DS_NOME" TEXT NOT NULL,
    "NR_CNPJ" TEXT NOT NULL,
    "NR_CPF" TEXT NOT NULL,
    "DS_ATIVO" TEXT NOT NULL,
    "NR_MES_NIVER" INTEGER NOT NULL,
    "NR_DIA_NIVER" INTEGER NOT NULL,
    "DT_NASCIMENTO" TEXT NOT NULL,
    "TP_SEXO" TEXT NOT NULL,
    "TP_PESSOA" TEXT NOT NULL,
    "TP_SIT_JURIDICA" TEXT NOT NULL,
    "DS_INSTAGRAM" TEXT NOT NULL,
    "DS_FACEBOOK" TEXT NOT NULL,
    "DS_LINKEDIN" TEXT NOT NULL,
    "DS_EMAIL" TEXT NOT NULL,
    "NR_DDD_CEL" TEXT NOT NULL,
    "NR_CELULAR" TEXT NOT NULL,
    "NR_ENDERECO" TEXT NOT NULL,
    "DS_COMPLEMENTO" TEXT NOT NULL,
    "IMG_FOTO" TEXT NOT NULL,
    "VL_MEDIO" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_REVENDA_pkey" PRIMARY KEY ("ID_REVENDA")
);

-- CreateTable
CREATE TABLE "TB_CLIENTE" (
    "ID_CLIENTE" TEXT NOT NULL,
    "ID_REVENDA" INTEGER NOT NULL,
    "ID_ENDERECO" INTEGER NOT NULL,
    "NR_CARTEIRA" INTEGER NOT NULL,
    "VL_CARTEIRA" INTEGER NOT NULL,
    "DS_FANTASIA" TEXT NOT NULL,
    "DS_CLIENTE" TEXT NOT NULL,
    "NR_CNPJ" TEXT NOT NULL,
    "NR_CPF" TEXT NOT NULL,
    "NR_RG" TEXT NOT NULL,
    "NR_MES_NIVER" INTEGER NOT NULL,
    "NR_DIA_NIVER" INTEGER NOT NULL,
    "DT_NASCIMENTO" TIMESTAMP(3) NOT NULL,
    "DS_EMAIL" TEXT NOT NULL,
    "NR_DDD_CEL" TEXT NOT NULL,
    "NR_CELULAR" TEXT NOT NULL,
    "NR_DDD_TEL" TEXT NOT NULL,
    "NR_TELEFONE" TEXT NOT NULL,
    "CD_MUNICIPIO" TEXT NOT NULL,
    "DS_COMPLEMENTO" TEXT NOT NULL,
    "DS_LOGRADOURO" TEXT NOT NULL,
    "DS_BAIRRO" TEXT NOT NULL,
    "DS_CIDADE" TEXT NOT NULL,
    "DS_UF" TEXT NOT NULL,
    "NR_ENDERECO" TEXT NOT NULL,
    "NR_CEP" TEXT NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_CONTRATO" TIMESTAMP(3),
    "DT_RECISAO" TIMESTAMP(3),
    "ID_MOTIVO" INTEGER NOT NULL,
    "VL_CONTRATO" INTEGER NOT NULL,
    "VL_MENSAL" INTEGER NOT NULL,
    "TP_ATIVO" TEXT NOT NULL,
    "TP_SEXO" TEXT NOT NULL,
    "TP_PESSOA" TEXT NOT NULL,
    "TP_REGIME" TEXT NOT NULL,
    "NR_INSC_ESTADUAL_SUBST" TEXT NOT NULL,
    "NR_INSC_ESTADUAL" TEXT NOT NULL,
    "NR_INSC_MUNICIPAL" TEXT NOT NULL,
    "DS_SUFRAMA" TEXT NOT NULL,
    "DT_INCLUSAO" TEXT NOT NULL,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_CLIENTE_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "TB_MOTIVO" (
    "ID_MOTIVO" TEXT NOT NULL,
    "DS_MOTIVO" TEXT NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_MOTIVO_pkey" PRIMARY KEY ("ID_MOTIVO")
);

-- CreateTable
CREATE TABLE "TB_COMISSAO" (
    "ID_COMISSAO" TEXT NOT NULL,
    "TP_COMISSAO" TEXT NOT NULL,
    "TP_UPLINE" TEXT NOT NULL,
    "NV_UPLINE" TEXT NOT NULL,
    "VL_MEDIO" INTEGER NOT NULL,
    "VL_COMISSAO" INTEGER NOT NULL,
    "NR_CARTEIRA" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_COMISSAO_pkey" PRIMARY KEY ("ID_COMISSAO")
);

-- CreateTable
CREATE TABLE "TB_TREINAMENTO" (
    "ID_TREINAMENTO" TEXT NOT NULL,
    "DS_TREINAMENTO" TEXT NOT NULL,
    "DS_IMAGEM" TEXT NOT NULL,
    "VL_AVALIADO" INTEGER NOT NULL,
    "VL_CURSO" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_TREINAMENTO_pkey" PRIMARY KEY ("ID_TREINAMENTO")
);

-- CreateTable
CREATE TABLE "TB_PRECO" (
    "ID_PRECO" TEXT NOT NULL,
    "DS_SERVICO" TEXT NOT NULL,
    "VL_SERVICO" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_PRECO_pkey" PRIMARY KEY ("ID_PRECO")
);

-- CreateTable
CREATE TABLE "TB_RECEITA" (
    "ID_RECEITA" TEXT NOT NULL,
    "NR_ANO" TEXT NOT NULL,
    "DS_MES" TEXT NOT NULL,
    "VL_MES" INTEGER NOT NULL,
    "VL_META" INTEGER NOT NULL,
    "DT_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,
    "DT_ULT_ALTERACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USER_ULT_ALT" TEXT NOT NULL,

    CONSTRAINT "TB_RECEITA_pkey" PRIMARY KEY ("ID_RECEITA")
);

-- CreateIndex
CREATE UNIQUE INDEX "tb_ativos_ID_USER_ULT_ALT_key" ON "tb_ativos"("ID_USER_ULT_ALT");

-- CreateIndex
CREATE UNIQUE INDEX "TB_EXECUTIVO_NR_CPF_key" ON "TB_EXECUTIVO"("NR_CPF");

-- CreateIndex
CREATE UNIQUE INDEX "TB_EXECUTIVO_NR_CNPJ_key" ON "TB_EXECUTIVO"("NR_CNPJ");

-- CreateIndex
CREATE UNIQUE INDEX "TB_REVENDA_NR_CNPJ_key" ON "TB_REVENDA"("NR_CNPJ");

-- CreateIndex
CREATE UNIQUE INDEX "TB_REVENDA_NR_CPF_key" ON "TB_REVENDA"("NR_CPF");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CLIENTE_NR_CNPJ_key" ON "TB_CLIENTE"("NR_CNPJ");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CLIENTE_NR_CPF_key" ON "TB_CLIENTE"("NR_CPF");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CLIENTE_NR_RG_key" ON "TB_CLIENTE"("NR_RG");
